# https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "minimum2scp"
      - "nagachika"
      - "akm"

